/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutDashboardImport } from './routes/_layout-dashboard'
import { Route as LayoutDashboardIndexImport } from './routes/_layout-dashboard/index'

// Create/Update Routes

const LayoutDashboardRoute = LayoutDashboardImport.update({
  id: '/_layout-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const LayoutDashboardIndexRoute = LayoutDashboardIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout-dashboard': {
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof rootRoute
    }
    '/_layout-dashboard/': {
      preLoaderRoute: typeof LayoutDashboardIndexImport
      parentRoute: typeof LayoutDashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutDashboardRoute.addChildren([LayoutDashboardIndexRoute]),
])

/* prettier-ignore-end */
